FROM fedora:30
ENV TERM=xterm
WORKDIR /usr/local/src/pam_usb

RUN dnf upgrade --refresh -y
RUN dnf install -y gcc make rsync libxml2-devel pam-devel libudisks2-devel glib2-devel python3-gobject rpmdevtools rpmlint