.TH pamusb-keyring-unlock-gnome 1 "November 06, 2021" "" "PAM_USB"

.SH NAME
\fBpamusb-keyring-unlock-gnome \fP- pam_usb unlock tool for the gnome-keyring
.SH DESCRIPTION
\fBpamusb-keyring-unlock-gnome\fP is a tool to unlock your GNOME keyring when used with pam_usb autologin.
.SH CONFIGURATION
See the pam_usb Wiki <https://github.com/mcdope/pam_usb/wiki> for details about how to configure this feature.
.SH BUGS
Please post bug reports on the Github issue tracker.
.SH AUTHOR
Tobias Bäumer <tobiasbaeumer@gmail.com>
